import { Employee, MenuItem, Category, Order, Table, Reservation, Shift, Transaction, Discount, Stock } from './types'

export const employees: Employee[] = [
  {
    id: 'emp1',
    name: 'Richardo Wilson',
    role: 'admin',
    email: 'richardo@restaurant.com',
    phone: '+1234567890',
    pin: '123456',
    avatar: '/avatars/richardo.jpg',
    shiftTime: '10:00 AM - 02:00 PM',
    status: 'active',
    lastLogin: new Date('2024-02-24T10:00:00'),
  },
  {
    id: 'emp2',
    name: 'Sarah Johnson',
    role: 'admin',
    email: 'sarah@restaurant.com',
    phone: '+1234567891',
    pin: '234567',
    avatar: '/avatars/sarah.jpg',
    shiftTime: '02:00 PM - 10:00 PM',
    status: 'active',
    lastLogin: new Date('2024-02-23T14:00:00'),
  },
  {
    id: 'emp3',
    name: 'Michael Chen',
    role: 'manager',
    email: 'michael@restaurant.com',
    phone: '+1234567892',
    pin: '345678',
    avatar: '/avatars/michael.jpg',
    shiftTime: '09:00 AM - 05:00 PM',
    status: 'active',
    lastLogin: new Date('2024-02-24T09:00:00'),
  },
  {
    id: 'emp4',
    name: 'Emily Davis',
    role: 'manager',
    email: 'emily@restaurant.com',
    phone: '+1234567893',
    pin: '456789',
    avatar: '/avatars/emily.jpg',
    shiftTime: '05:00 PM - 01:00 AM',
    status: 'active',
  },
  {
    id: 'emp5',
    name: 'Daniel Martinez',
    role: 'cashier',
    email: 'daniel@restaurant.com',
    phone: '+1234567894',
    pin: '567890',
    avatar: '/avatars/daniel.jpg',
    shiftTime: '08:00 AM - 04:00 PM',
    status: 'active',
  },
  {
    id: 'emp6',
    name: 'Alexandra Brown',
    role: 'cashier',
    email: 'alexandra@restaurant.com',
    phone: '+1234567895',
    pin: '678901',
    avatar: '/avatars/alexandra.jpg',
    shiftTime: '04:00 PM - 12:00 AM',
    status: 'active',
  },
  {
    id: 'emp7',
    name: 'James Wilson',
    role: 'cashier',
    email: 'james@restaurant.com',
    phone: '+1234567896',
    pin: '789012',
    avatar: '/avatars/james.jpg',
    shiftTime: '12:00 PM - 08:00 PM',
    status: 'active',
  },
  {
    id: 'emp8',
    name: 'Lisa Anderson',
    role: 'kitchen',
    email: 'lisa@restaurant.com',
    phone: '+1234567897',
    pin: '890123',
    avatar: '/avatars/lisa.jpg',
    shiftTime: '07:00 AM - 03:00 PM',
    status: 'active',
  },
]

export const categories: Category[] = [
  { id: 'cat1', name: 'Food', description: 'Main dishes and appetizers', itemCount: 12 },
  { id: 'cat2', name: 'Beverage', description: 'Drinks and refreshments', itemCount: 6 },
  { id: 'cat3', name: 'Additional', description: 'Extras and sides', itemCount: 2 },
]

export const menuItems: MenuItem[] = [
  {
    id: 'item1',
    code: 'F001',
    name: 'Belgian Waffles',
    category: 'Food',
    price: 32.00,
    costPrice: 15.00,
    image: '/menu/waffles.jpg',
    stock: 50,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item2',
    code: 'F002',
    name: 'Creamy Garlic Chicken',
    category: 'Food',
    price: 60.00,
    costPrice: 28.00,
    image: '/menu/chicken.jpg',
    stock: 30,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item3',
    code: 'F003',
    name: 'Spicy Tuna Tartare',
    category: 'Food',
    price: 28.00,
    costPrice: 14.00,
    image: '/menu/tuna.jpg',
    stock: 25,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item4',
    code: 'F004',
    name: 'Grilled Salmon',
    category: 'Food',
    price: 75.00,
    costPrice: 35.00,
    stock: 20,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item5',
    code: 'F005',
    name: 'Beef Burger Deluxe',
    category: 'Food',
    price: 45.00,
    costPrice: 20.00,
    stock: 40,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item6',
    code: 'F006',
    name: 'Caesar Salad',
    category: 'Food',
    price: 25.00,
    costPrice: 10.00,
    stock: 35,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item7',
    code: 'F007',
    name: 'Margherita Pizza',
    category: 'Food',
    price: 55.00,
    costPrice: 22.00,
    stock: 15,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item8',
    code: 'F008',
    name: 'Pasta Carbonara',
    category: 'Food',
    price: 48.00,
    costPrice: 18.00,
    stock: 30,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item9',
    code: 'F009',
    name: 'Ribeye Steak',
    category: 'Food',
    price: 95.00,
    costPrice: 45.00,
    stock: 12,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item10',
    code: 'F010',
    name: 'Fish and Chips',
    category: 'Food',
    price: 42.00,
    costPrice: 19.00,
    stock: 28,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item11',
    code: 'F011',
    name: 'Chicken Wings',
    category: 'Food',
    price: 35.00,
    costPrice: 15.00,
    stock: 45,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item12',
    code: 'F012',
    name: 'Mushroom Risotto',
    category: 'Food',
    price: 52.00,
    costPrice: 23.00,
    stock: 20,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item13',
    code: 'B001',
    name: 'Classic Lemonade',
    category: 'Beverage',
    price: 12.00,
    costPrice: 4.00,
    stock: 100,
    unit: 'glass',
    status: 'active',
  },
  {
    id: 'item14',
    code: 'B002',
    name: 'Iced Coffee',
    category: 'Beverage',
    price: 15.00,
    costPrice: 5.00,
    stock: 80,
    unit: 'glass',
    status: 'active',
  },
  {
    id: 'item15',
    code: 'B003',
    name: 'Fresh Orange Juice',
    category: 'Beverage',
    price: 18.00,
    costPrice: 7.00,
    stock: 60,
    unit: 'glass',
    status: 'active',
  },
  {
    id: 'item16',
    code: 'B004',
    name: 'Cappuccino',
    category: 'Beverage',
    price: 16.00,
    costPrice: 6.00,
    stock: 90,
    unit: 'cup',
    status: 'active',
  },
  {
    id: 'item17',
    code: 'B005',
    name: 'Green Tea',
    category: 'Beverage',
    price: 10.00,
    costPrice: 3.00,
    stock: 100,
    unit: 'cup',
    status: 'active',
  },
  {
    id: 'item18',
    code: 'B006',
    name: 'Mineral Water',
    category: 'Beverage',
    price: 8.00,
    costPrice: 2.00,
    stock: 150,
    unit: 'bottle',
    status: 'active',
  },
  {
    id: 'item19',
    code: 'A001',
    name: 'French Fries',
    category: 'Additional',
    price: 15.00,
    costPrice: 6.00,
    stock: 70,
    unit: 'pcs',
    status: 'active',
  },
  {
    id: 'item20',
    code: 'A002',
    name: 'Garlic Bread',
    category: 'Additional',
    price: 12.00,
    costPrice: 5.00,
    stock: 50,
    unit: 'pcs',
    status: 'active',
  },
]

export const tables: Table[] = [
  { id: 'tbl1', number: 'A1', section: 'A', capacity: 2, status: 'available' },
  { id: 'tbl2', number: 'A2', section: 'A', capacity: 4, status: 'occupied', currentOrderId: 'ord1' },
  { id: 'tbl3', number: 'A3', section: 'A', capacity: 4, status: 'available' },
  { id: 'tbl4', number: 'A4', section: 'A', capacity: 6, status: 'reserved' },
  { id: 'tbl5', number: 'A5', section: 'A', capacity: 2, status: 'occupied', currentOrderId: 'ord2' },
  { id: 'tbl6', number: 'A6', section: 'A', capacity: 4, status: 'cleaning' },
  { id: 'tbl7', number: 'B1', section: 'B', capacity: 2, status: 'available' },
  { id: 'tbl8', number: 'B2', section: 'B', capacity: 4, status: 'occupied', currentOrderId: 'ord3' },
  { id: 'tbl9', number: 'B3', section: 'B', capacity: 6, status: 'available' },
  { id: 'tbl10', number: 'B4', section: 'B', capacity: 4, status: 'available' },
  { id: 'tbl11', number: 'B5', section: 'B', capacity: 8, status: 'reserved' },
  { id: 'tbl12', number: 'B6', section: 'B', capacity: 2, status: 'occupied', currentOrderId: 'ord4' },
]

export const orders: Order[] = [
  {
    id: 'ord1',
    orderNumber: 'DI008',
    customerName: 'Daniel',
    tableId: 'tbl2',
    tableNumber: 'A2',
    orderType: 'dine-in',
    items: [
      { id: 'oi1', menuItemId: 'item1', name: 'Belgian Waffles', price: 32.00, quantity: 2, status: 'cooking' },
      { id: 'oi2', menuItemId: 'item13', name: 'Classic Lemonade', price: 12.00, quantity: 3, status: 'ready' },
      { id: 'oi3', menuItemId: 'item2', name: 'Creamy Garlic Chicken', price: 60.00, quantity: 4, status: 'cooking' },
      { id: 'oi4', menuItemId: 'item3', name: 'Spicy Tuna Tartare', price: 28.00, quantity: 1, status: 'pending' },
    ],
    subtotal: 360.00,
    discount: 0,
    tax: 39.60,
    serviceCharge: 18.00,
    total: 417.60,
    status: 'in-progress',
    progress: 10,
    createdAt: new Date('2024-02-17T15:43:00'),
    updatedAt: new Date('2024-02-17T15:43:00'),
    cashierId: 'emp5',
  },
  {
    id: 'ord2',
    orderNumber: 'TA001',
    customerName: 'Vlona',
    orderType: 'take-away',
    items: [
      { id: 'oi5', menuItemId: 'item1', name: 'Belgian Waffles', price: 32.00, quantity: 2, status: 'cooking' },
      { id: 'oi6', menuItemId: 'item13', name: 'Classic Lemonade', price: 12.00, quantity: 3, status: 'ready' },
      { id: 'oi7', menuItemId: 'item2', name: 'Creamy Garlic Chicken', price: 60.00, quantity: 4, status: 'cooking' },
      { id: 'oi8', menuItemId: 'item3', name: 'Spicy Tuna Tartare', price: 28.00, quantity: 1, status: 'pending' },
    ],
    subtotal: 332.00,
    discount: 0,
    tax: 36.52,
    serviceCharge: 16.60,
    total: 385.12,
    status: 'in-progress',
    progress: 60,
    createdAt: new Date('2024-02-17T14:56:00'),
    updatedAt: new Date('2024-02-17T14:56:00'),
    cashierId: 'emp5',
  },
  {
    id: 'ord3',
    orderNumber: 'DI103',
    customerName: 'Nielson',
    tableId: 'tbl8',
    tableNumber: 'B2',
    orderType: 'dine-in',
    items: [
      { id: 'oi9', menuItemId: 'item1', name: 'Belgian Waffles', price: 32.00, quantity: 2, status: 'ready' },
      { id: 'oi10', menuItemId: 'item13', name: 'Classic Lemonade', price: 12.00, quantity: 3, status: 'ready' },
      { id: 'oi11', menuItemId: 'item2', name: 'Creamy Garlic Chicken', price: 60.00, quantity: 4, status: 'ready' },
      { id: 'oi12', menuItemId: 'item3', name: 'Spicy Tuna Tartare', price: 28.00, quantity: 1, status: 'ready' },
    ],
    subtotal: 332.00,
    discount: 0,
    tax: 36.52,
    serviceCharge: 16.60,
    total: 385.12,
    status: 'in-progress',
    progress: 40,
    createdAt: new Date('2024-02-17T13:24:00'),
    updatedAt: new Date('2024-02-17T13:24:00'),
    cashierId: 'emp5',
  },
  {
    id: 'ord4',
    orderNumber: 'DI002',
    customerName: 'Eve',
    tableId: 'tbl12',
    tableNumber: 'B6',
    orderType: 'dine-in',
    items: [
      { id: 'oi13', menuItemId: 'item1', name: 'Belgian Waffles', price: 32.00, quantity: 2, status: 'ready' },
      { id: 'oi14', menuItemId: 'item13', name: 'Classic Lemonade', price: 12.00, quantity: 3, status: 'ready' },
      { id: 'oi15', menuItemId: 'item2', name: 'Creamy Garlic Chicken', price: 60.00, quantity: 4, status: 'ready' },
      { id: 'oi16', menuItemId: 'item3', name: 'Spicy Tuna Tartare', price: 28.00, quantity: 1, status: 'ready' },
    ],
    subtotal: 332.00,
    discount: 0,
    tax: 36.52,
    serviceCharge: 16.60,
    total: 385.12,
    status: 'waiting-payment',
    progress: 100,
    createdAt: new Date('2024-02-17T12:24:00'),
    updatedAt: new Date('2024-02-17T12:24:00'),
    cashierId: 'emp5',
  },
  {
    id: 'ord5',
    orderNumber: 'DI104',
    customerName: 'Alexandra',
    tableId: 'tbl3',
    tableNumber: 'A3',
    orderType: 'dine-in',
    items: [
      { id: 'oi17', menuItemId: 'item4', name: 'Grilled Salmon', price: 75.00, quantity: 2, status: 'cooking' },
      { id: 'oi18', menuItemId: 'item14', name: 'Iced Coffee', price: 15.00, quantity: 2, status: 'ready' },
    ],
    subtotal: 180.00,
    discount: 0,
    tax: 19.80,
    serviceCharge: 9.00,
    total: 208.80,
    status: 'in-progress',
    progress: 50,
    createdAt: new Date('2024-02-17T11:24:00'),
    updatedAt: new Date('2024-02-17T11:24:00'),
    cashierId: 'emp6',
  },
  {
    id: 'ord6',
    orderNumber: 'DI101',
    customerName: 'Daniel',
    tableId: 'tbl1',
    tableNumber: 'A1',
    orderType: 'dine-in',
    items: [
      { id: 'oi19', menuItemId: 'item5', name: 'Beef Burger Deluxe', price: 45.00, quantity: 1, status: 'ready' },
      { id: 'oi20', menuItemId: 'item19', name: 'French Fries', price: 15.00, quantity: 1, status: 'ready' },
      { id: 'oi21', menuItemId: 'item14', name: 'Iced Coffee', price: 15.00, quantity: 1, status: 'ready' },
    ],
    subtotal: 75.00,
    discount: 0,
    tax: 8.25,
    serviceCharge: 3.75,
    total: 87.00,
    status: 'waiting-payment',
    progress: 100,
    createdAt: new Date('2024-02-17T10:11:00'),
    updatedAt: new Date('2024-02-17T10:11:00'),
    cashierId: 'emp5',
  },
]

export const reservations: Reservation[] = [
  {
    id: 'res1',
    customerName: 'John Smith',
    phone: '+1234567890',
    date: new Date('2024-02-25'),
    time: '19:00',
    partySize: 4,
    tableId: 'tbl4',
    tableNumber: 'A4',
    status: 'confirmed',
    notes: 'Birthday celebration',
    createdAt: new Date('2024-02-20'),
  },
  {
    id: 'res2',
    customerName: 'Emma Wilson',
    phone: '+1234567891',
    date: new Date('2024-02-25'),
    time: '20:00',
    partySize: 2,
    tableId: 'tbl7',
    tableNumber: 'B1',
    status: 'confirmed',
    createdAt: new Date('2024-02-21'),
  },
  {
    id: 'res3',
    customerName: 'Robert Brown',
    phone: '+1234567892',
    date: new Date('2024-02-26'),
    time: '18:30',
    partySize: 6,
    tableId: 'tbl11',
    tableNumber: 'B5',
    status: 'pending',
    notes: 'Window seat preferred',
    createdAt: new Date('2024-02-22'),
  },
  {
    id: 'res4',
    customerName: 'Maria Garcia',
    phone: '+1234567893',
    date: new Date('2024-02-26'),
    time: '19:30',
    partySize: 4,
    status: 'confirmed',
    createdAt: new Date('2024-02-23'),
  },
  {
    id: 'res5',
    customerName: 'David Lee',
    phone: '+1234567894',
    date: new Date('2024-02-27'),
    time: '20:00',
    partySize: 8,
    status: 'pending',
    notes: 'Corporate dinner',
    createdAt: new Date('2024-02-23'),
  },
]

export const discounts: Discount[] = [
  {
    id: 'disc1',
    name: 'Weekend Special',
    code: 'WEEKEND20',
    type: 'percentage',
    value: 20,
    minOrderAmount: 100,
    validFrom: new Date('2024-02-24'),
    validTo: new Date('2024-02-25'),
    usageLimit: 100,
    usageCount: 45,
    applicableTo: 'all',
    status: 'active',
  },
  {
    id: 'disc2',
    name: 'Lunch Deal',
    code: 'LUNCH15',
    type: 'percentage',
    value: 15,
    minOrderAmount: 50,
    validFrom: new Date('2024-02-01'),
    validTo: new Date('2024-02-29'),
    usageLimit: 500,
    usageCount: 234,
    applicableTo: 'category',
    applicableItems: ['cat1'],
    status: 'active',
  },
  {
    id: 'disc3',
    name: 'New Customer',
    code: 'WELCOME10',
    type: 'nominal',
    value: 10,
    validFrom: new Date('2024-02-01'),
    validTo: new Date('2024-12-31'),
    usageLimit: 1000,
    usageCount: 156,
    applicableTo: 'all',
    status: 'active',
  },
  {
    id: 'disc4',
    name: 'Happy Hour',
    code: 'HAPPY25',
    type: 'percentage',
    value: 25,
    minOrderAmount: 30,
    validFrom: new Date('2024-02-01'),
    validTo: new Date('2024-02-29'),
    usageLimit: 200,
    usageCount: 89,
    applicableTo: 'category',
    applicableItems: ['cat2'],
    status: 'active',
  },
  {
    id: 'disc5',
    name: 'Birthday Special',
    code: 'BDAY50',
    type: 'nominal',
    value: 50,
    minOrderAmount: 200,
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2024-12-31'),
    usageCount: 23,
    applicableTo: 'all',
    status: 'active',
  },
]

export const shifts: Shift[] = [
  {
    id: 'shift1',
    cashierId: 'emp5',
    cashierName: 'Daniel Martinez',
    openTime: new Date('2024-02-24T08:00:00'),
    openingCash: 500,
    expectedCash: 1850,
    totalSales: 1400,
    totalCash: 850,
    totalNonCash: 550,
    totalTransactions: 12,
    status: 'open',
  },
  {
    id: 'shift2',
    cashierId: 'emp6',
    cashierName: 'Alexandra Brown',
    openTime: new Date('2024-02-23T16:00:00'),
    closeTime: new Date('2024-02-24T00:00:00'),
    openingCash: 500,
    closingCash: 2320,
    expectedCash: 2300,
    totalSales: 1800,
    totalCash: 1200,
    totalNonCash: 600,
    totalTransactions: 18,
    difference: 20,
    status: 'closed',
  },
]

export const transactions: Transaction[] = Array.from({ length: 30 }, (_, i) => ({
  id: `trans${i + 1}`,
  orderNumber: `DI${String(i + 1).padStart(3, '0')}`,
  date: new Date(Date.now() - i * 24 * 60 * 60 * 1000),
  cashierId: employees[Math.floor(Math.random() * 3) + 4].id,
  cashierName: employees[Math.floor(Math.random() * 3) + 4].name,
  customerName: ['John', 'Emma', 'Robert', 'Maria', 'David'][Math.floor(Math.random() * 5)],
  tableNumber: i % 3 === 0 ? undefined : `A${(i % 6) + 1}`,
  orderType: i % 3 === 0 ? 'take-away' : 'dine-in',
  itemsCount: Math.floor(Math.random() * 5) + 2,
  subtotal: Math.floor(Math.random() * 200) + 50,
  discount: Math.floor(Math.random() * 20),
  tax: 0,
  serviceCharge: 0,
  total: 0,
  paymentMethod: ['cash', 'qris', 'debit', 'transfer'][Math.floor(Math.random() * 4)] as any,
  status: 'completed',
})).map(t => ({
  ...t,
  tax: t.subtotal * 0.11,
  serviceCharge: t.subtotal * 0.05,
  total: t.subtotal - t.discount + (t.subtotal * 0.11) + (t.subtotal * 0.05),
}))

export const stocks: Stock[] = [
  { id: 'stock1', name: 'Chicken Breast', unit: 'kg', currentStock: 25, minStock: 10, lastRestocked: new Date('2024-02-20') },
  { id: 'stock2', name: 'Salmon Fillet', unit: 'kg', currentStock: 8, minStock: 5, lastRestocked: new Date('2024-02-22') },
  { id: 'stock3', name: 'Beef Patty', unit: 'pcs', currentStock: 45, minStock: 20, lastRestocked: new Date('2024-02-21') },
  { id: 'stock4', name: 'Lettuce', unit: 'kg', currentStock: 12, minStock: 5, lastRestocked: new Date('2024-02-23') },
  { id: 'stock5', name: 'Tomatoes', unit: 'kg', currentStock: 15, minStock: 8, lastRestocked: new Date('2024-02-23') },
  { id: 'stock6', name: 'Coffee Beans', unit: 'kg', currentStock: 6, minStock: 3, lastRestocked: new Date('2024-02-19') },
  { id: 'stock7', name: 'Orange', unit: 'kg', currentStock: 20, minStock: 10, lastRestocked: new Date('2024-02-24') },
  { id: 'stock8', name: 'Lemon', unit: 'kg', currentStock: 10, minStock: 5, lastRestocked: new Date('2024-02-24') },
]
